language: node_js
node_js: node
dist: xenial
os: linux

before_install:
  - sudo apt-get install g++ build-essential -y
  - sudo apt-get install make -y

before_script:
  - npm install -g @angular/cli

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: "Unit Tests"

      script: npm run test-headless
    - stage: test
      name: "Linting"
      script: ng lint

    - stage: build
      if: branch = master
      name: "Build frontend"
      script: "ng build --prod"
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: dist/*
        file_glob: true
